In [3]:
import numpy as np

In [22]:
A = np.array(([1, 2, 3],
              [3, 4, -3],
              [9, -7, 2]))

In [16]:
print(A)

[[1 2 4]
 [3 4 7]
 [5 6 9]]


In [21]:
# A'nın boyutları
A.shape

(3, 3)

In [18]:
print(A[1:3][0:3])

[[3 4 7]
 [5 6 9]]


In [22]:
det = np.linalg.det(A)
print(det)

2.000000000000003


# Lineer sistem

$$ Ax = b $$

In [6]:
def cramer (A, b):
    
    # A: katsayılar matrisi
    # b: sonuçlar matrisi
    # x: bilinmeyenlerin vektörü
        
    # Önce A'nın matris b'nin de vektör olduğundan emin olalım.
    if len(A.shape) != 2 or len(b.shape) != 1:
        print("A'nın matris olduğundan emin olun")
        return None
    
    # A kare mi?
    
    if A.shape[0] != A.shape[1]:
        print("A kare matris değil")
        return None
    
    # A ve b'nin boyutları uyumlu mu?
    
    if A.shape[0] != b.shape[0]:
        print("A ve b boyutları uyumsuz")
        return None
    
    x = np.zeros(A.shape[0])
    
    A_i = np.zeros_like(A)
    
    for i in range(A.shape[0]):
        A_i = A.copy()
        A_i[:,i] = b
        x[i] = np.linalg.det(A_i) / np.linalg.det(A)
        
    return x
    

In [4]:
A = np.array([[1,-2,3,7], [3,4,-3,1],[9,-7,3,1],[2,-5,1,4]])
b = np.array([-2,1,4,1])

print(np.linalg.det(A))

-1183.9999999999998


In [8]:
x = cramer(A, b)
print(x)

[ 0.37246622 -0.32939189 -0.47635135 -0.22888514]


In [9]:
x1 = np.linalg.solve(A,b)
print(x1)

[ 0.37246622 -0.32939189 -0.47635135 -0.22888514]


# Matris Operasyonları

In [23]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
A.shape

(3, 3)

In [12]:
print(A[1])

[4 5 6]


In [11]:
print(A[:,1])

[2 5 8]


In [13]:
B = A

In [17]:
B[2,:] = [0, 0, 0]

In [18]:
print(A)

[[1 2 3]
 [4 5 6]
 [0 0 0]]


In [24]:
C = A.copy()

In [25]:
C[2,:] = [0,0,0]

In [26]:
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
A[1,:], A[2,:] = A[2,:].copy(), A[1,:].copy() # swap rows 1 and 2

In [29]:
print(A)

[[1 2 3]
 [7 8 9]
 [4 5 6]]


In [30]:
print(A.T)

[[1 7 4]
 [2 8 5]
 [3 9 6]]


In [31]:
B = A.T.copy()

In [32]:
print(B)

[[1 7 4]
 [2 8 5]
 [3 9 6]]


In [35]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[9,8,7],[6,5,4],[3,2,1]])

C = np.dot(A, B)

print(C)


[[ 30  24  18]
 [ 84  69  54]
 [138 114  90]]


In [37]:
D = A * B
print(D)

[[ 9 16 21]
 [24 25 24]
 [21 16  9]]


In [39]:
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
b = np.array([-1, -2, -3])

Ab = np.column_stack((A, b))
print(Ab)

[[ 1  2  3 -1]
 [ 4  5  6 -2]
 [ 7  8  9 -3]]
